import = ["~/.config/alacritty/rose-pine.toml"]

[font]
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
option_as_alt = "None"
title = "Probably Mistakes"
opacity = 0.90
blur = true
padding.x = 8
padding.y = 4


[cursor]
style.blinking = "On"

[mouse]
hide_when_typing = true
