import = ["~/.config/alacritty/rose-pine.toml"]

[font]
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
option_as_alt = "None"
title = "GigaTerm"
opacity = 0.65
blur = true


