general.import = ["~/.config/alacritty/colors/kanagawa_dragon.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"



[window]
decorations = "Buttonless"
option_as_alt = "None"
title = "Probably Mistakes"
opacity = 0.80
blur = true
dynamic_padding = true
padding.x = 2


[cursor]
style.blinking = "On"

[mouse]
hide_when_typing = false

