import = ["/home/bmcgahan/.config/alacritty/oxocarbon.toml"]

[font]
animation = "EaseOutExpo"
blink_interval = 750
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "none"
option_as_alt = "None"
title = "GigaTerm"

[window.padding]
x = 4
y = 8
