#!/usr/bin/env bash

selected=$(find ~/personal ~/school ~/.dotfiles ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z $selected ]]; then
    exit 0
fi


selected_name=$(basename "$selected" | tr . _)
zellij_running=$(pgrep zellij)

if [[ $zellij_running ]]; then
    if zellij ls | grep $selected_name; then
        zellij a $selected_name
    else 
        zellij -s $selected_name
    fi
else
    if zellij ls | grep $selected_name; then
        zellij a $selected_name
    else 
        zellij -s $selected_name
    fi
fi

# if [[$tmux_running > 1]]; then
#         tmux detach
#         if tmux ls | grep $selected_name; then
#             tmux a $selected_name
#     else
#             cd $selected
#             tmux new-session -t $selected_name
#         fi
# else
#         if tmux ls | grep $selected_name; then
#             tmux a $selected_name
#     else
#             cd $selected
#             tmux new-session -t $selected_name
#         fi
# fi





