-- vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme tokyonight")
-- vim.cmd("colorscheme rose-pine")
-- vim.cmd("colorscheme onedark")
-- vim.cmd("colorscheme gruvbox")
vim.cmd.colorscheme("gruvbox-material")
